### ISSUE TITLE
ReadMe中的userdata文件夹请问是在哪个地方？

### ISSUE THREAD

**Issue by jhqz103** [luiges90/ZHSAN3#2]
把userdata裡的內容複製至%APP_DATA%\Roaming\Godot\app_userdata\ZHSAN3資料夾。可手動新建資料夾。(第一次運行時Godot會自動建立這個資料夾)
项目中似乎找不到userdata文件夹

**Comment by luiges90** [comment]
這個已經過時了，可以不用管 😅
