### ISSUE TITLE
列表bug

### ISSUE THREAD

**Issue by jhqz103** [luiges90/ZHSAN3#4]
UIMain/TabList/TabList.gd 73行至76行
該段代碼會導致内政選人物時，如果手動取消所有人物的選擇，右下角確定按鈕不會變成禁用狀態。

該段代碼去掉後就正常，代碼機制和作用尚未熟悉，不敢亂改，先提個issue

**Comment by luiges90** [comment]
下次不要直接說行數，容易丟失。應該直接引用代碼。
if _max_selection == 1 這段是處理只限單選的情況，內政是多選應該不會執行的
